#include "resample.h"

//That thing was generated by an llm because i couldn't figure it out. it somehow works, and i still have no idea
//how or why it does, but i'm going to use it anyway. sorry not sorry.

int resample_linear(const short *in, int in_samples, short *out, int out_samples, int channels, float ratio) {
    int out_index = 0;
    float pos = 0.0f;

    for (int i = 0; i < out_samples; i++) {
        int ipos = (int)pos;
        float frac = pos - ipos;

        if (ipos + 1 >= in_samples)
            break;

        for (int ch = 0; ch < channels; ch++) {
            int a = in[(ipos * channels) + ch];
            int b = in[((ipos + 1) * channels) + ch];
            out[(i * channels) + ch] = (short)((1.0f - frac) * a + frac * b);
        }

        pos += ratio;
        out_index++;
    }

    return out_index;
}
